version: "3.8"
services:
  backend_api:
    image: microdockr13/notionapp-backend_api
    restart: always
    build: ./server
    container_name: backend_api

  client:
    restart: always
    stdin_open: true
    tty: true
    build: ./app
    container_name: client
    depends_on:
      - backend_api

  nginx:
    restart: always
    build: ./nginx
    depends_on:
      - backend_api
      - client
    ports:
      - 8000:80
