version: "3.8"
services:
  backend_api:
    build:
      context: ./server
      args:
        NODE_ENV: development
    volumes:
      - ./server/src:/server/src
    environment:
      - NODE_ENV=development
    command: npm run dev
  client:
    build:
      context: ./app
      args:
        NODE_ENV: development
    volumes:
      - ./app/src:/app/src
    environment:
      - NODE_ENV=development
    command: npm run start
